apiVersion: apps/v1
kind: Deployment

metadata:
  name: azure-rag

spec:
  replicas: 1

  selector:
    matchLabels:
      app: azure-rag

  template:

    metadata:
      labels:
        app: azure-rag

    spec:

      containers:

      - name: azure-rag

        image: akspracticeacr26abin.azurecr.io/azure-rag:v1
        imagePullPolicy: Always

        ports:
        - containerPort: 8000

        env:

        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: ENVIRONMENT

        - name: AZURE_FOUNDRY_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: AZURE_FOUNDRY_ENDPOINT

        - name: AZURE_FOUNDRY_CHAT_DEPLOYMENT
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: AZURE_FOUNDRY_CHAT_DEPLOYMENT

        - name: AZURE_FOUNDRY_EMBEDDING_DEPLOYMENT
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: AZURE_FOUNDRY_EMBEDDING_DEPLOYMENT

        - name: AZURE_STORAGE_CONTAINER
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: AZURE_STORAGE_CONTAINER

        - name: AZURE_SEARCH_ENDPOINT
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: AZURE_SEARCH_ENDPOINT

        - name: AZURE_SEARCH_INDEX
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: AZURE_SEARCH_INDEX

        - name: CHUNK_SIZE
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: CHUNK_SIZE

        - name: CHUNK_OVERLAP
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: CHUNK_OVERLAP

        - name: KEY_VAULT_URL
          valueFrom:
            configMapKeyRef:
              name: rag-config
              key: KEY_VAULT_URL

        readinessProbe:

          httpGet:
            path: /health
            port: 8000

          initialDelaySeconds: 20

        livenessProbe:

          httpGet:
            path: /health
            port: 8000

          initialDelaySeconds: 30